### ISSUE TITLE
Project would benefit from more extensive README.md

### ISSUE THREAD

**Issue by triska** [Precisfice/DEDUCTION#2]
`README.md` could provide a nice introduction to the goals and current state of this work, with suitable links to interesting files that are already available in the repository.

**Comment by dcnorris** [comment]
Setting to work on the README today (Christmas Eve) as I await feedback on [this Scryer Q&A](https://github.com/mthom/scryer-prolog/discussions/2722#discussion-7739442).

**Comment by triska** [comment]
Thank you a lot! What a great day! 

Merry Christmas David and thank you for all this great work!

**Comment by dcnorris** [comment]
Merry Christmas to you, too, Markus!  Thank you for making all of this possible for me!

**Comment by triska** [comment]
Thank you a lot!
